import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faFacebookF,
  faInstagram,
  faLinkedinIn,
} from '@fortawesome/free-brands-svg-icons';
import { faUser } from '@fortawesome/free-regular-svg-icons';
import {
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowUp,
  faCaretRight,
  faCheck,
  faChevronLeft,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faMapMarkerAlt,
  faMinus,
  faPlus,
  faRocket,
  faShoppingBag,
  faTasks,
  faTimes,
  faUpload,
} from '@fortawesome/free-solid-svg-icons';

// Adds specific font awesome icons to fontawesome vue component so that they are available.
library.add(
  faAngleLeft,
  faAngleRight,
  faArrowDown,
  faArrowUp,
  faCaretRight,
  faCheck,
  faChevronLeft,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFacebookF,
  faInstagram,
  faLinkedinIn,
  faMapMarkerAlt,
  faMinus,
  faPlus,
  faRocket,
  faShoppingBag,
  faTasks,
  faTimes,
  faUpload,
  faUser,
);
